
package mx.com.msc.servicios.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Reportes", targetNamespace = "http://servicios.msc.mx.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Reportes {


    /**
     * 
     * @param extension
     * @param parametros
     * @param nombreReporte
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generaReporte", targetNamespace = "http://servicios.msc.mx.com/", className = "mx.com.msc.servicios.ws.GeneraReporte")
    @ResponseWrapper(localName = "generaReporteResponse", targetNamespace = "http://servicios.msc.mx.com/", className = "mx.com.msc.servicios.ws.GeneraReporteResponse")
    @Action(input = "http://servicios.msc.mx.com/Reportes/generaReporteRequest", output = "http://servicios.msc.mx.com/Reportes/generaReporteResponse")
    public String generaReporte(
        @WebParam(name = "nombreReporte", targetNamespace = "")
        String nombreReporte,
        @WebParam(name = "extension", targetNamespace = "")
        String extension,
        @WebParam(name = "parametros", targetNamespace = "")
        mx.com.msc.servicios.ws.GeneraReporte.Parametros parametros);

}
