
package mx.com.msc.servicios.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Reportes", targetNamespace = "http://servicios.msc.mx.com/", wsdlLocation = "http://localhost:8080/UtilsTecWs/Reportes?wsdl")
public class Reportes_Service
    extends Service
{

    private final static URL REPORTES_WSDL_LOCATION;
    private final static WebServiceException REPORTES_EXCEPTION;
    private final static QName REPORTES_QNAME = new QName("http://servicios.msc.mx.com/", "Reportes");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/UtilsTecWs/Reportes?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REPORTES_WSDL_LOCATION = url;
        REPORTES_EXCEPTION = e;
    }

    public Reportes_Service() {
        super(__getWsdlLocation(), REPORTES_QNAME);
    }

    public Reportes_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), REPORTES_QNAME, features);
    }

    public Reportes_Service(URL wsdlLocation) {
        super(wsdlLocation, REPORTES_QNAME);
    }

    public Reportes_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REPORTES_QNAME, features);
    }

    public Reportes_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Reportes_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Reportes
     */
    @WebEndpoint(name = "ReportesPort")
    public Reportes getReportesPort() {
        return super.getPort(new QName("http://servicios.msc.mx.com/", "ReportesPort"), Reportes.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Reportes
     */
    @WebEndpoint(name = "ReportesPort")
    public Reportes getReportesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicios.msc.mx.com/", "ReportesPort"), Reportes.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REPORTES_EXCEPTION!= null) {
            throw REPORTES_EXCEPTION;
        }
        return REPORTES_WSDL_LOCATION;
    }

}
