
package mx.com.msc.servicios.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SalasDisponiblesService", targetNamespace = "http://servicios.msc.mx.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SalasDisponiblesService {


    /**
     * 
     * @param horaFin
     * @param fechaPresentacion
     * @param horaInicio
     * @return
     *     returns java.util.List<mx.com.msc.servicios.ws.AnyTypeArray>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaSalasDisponibles", targetNamespace = "http://servicios.msc.mx.com/", className = "mx.com.msc.servicios.ws.ConsultaSalasDisponibles")
    @ResponseWrapper(localName = "consultaSalasDisponiblesResponse", targetNamespace = "http://servicios.msc.mx.com/", className = "mx.com.msc.servicios.ws.ConsultaSalasDisponiblesResponse")
    @Action(input = "http://servicios.msc.mx.com/SalasDisponiblesService/consultaSalasDisponiblesRequest", output = "http://servicios.msc.mx.com/SalasDisponiblesService/consultaSalasDisponiblesResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://servicios.msc.mx.com/SalasDisponiblesService/consultaSalasDisponibles/Fault/Exception")
    })
    public List<AnyTypeArray> consultaSalasDisponibles(
        @WebParam(name = "fechaPresentacion", targetNamespace = "")
        String fechaPresentacion,
        @WebParam(name = "horaInicio", targetNamespace = "")
        String horaInicio,
        @WebParam(name = "horaFin", targetNamespace = "")
        String horaFin)
        throws Exception_Exception
    ;

}
