
package mx.com.msc.servicios.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UsuariosService", targetNamespace = "http://servicios.msc.mx.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UsuariosService {


    /**
     * 
     * @param password
     * @param correo
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validaUsuario", targetNamespace = "http://servicios.msc.mx.com/", className = "mx.com.msc.servicios.ws.ValidaUsuario")
    @ResponseWrapper(localName = "validaUsuarioResponse", targetNamespace = "http://servicios.msc.mx.com/", className = "mx.com.msc.servicios.ws.ValidaUsuarioResponse")
    @Action(input = "http://servicios.msc.mx.com/UsuariosService/validaUsuarioRequest", output = "http://servicios.msc.mx.com/UsuariosService/validaUsuarioResponse")
    public int validaUsuario(
        @WebParam(name = "correo", targetNamespace = "")
        String correo,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
